### ISSUE TITLE
Codepen or jsfiddle demo link is needed

### ISSUE THREAD

**Issue by nurgasemetey** [Paraboly/pwc-map-legend#8]

**Comment by SchemeSonic** [comment]
assigning @WrathChaos

**Comment by kuraydev** [comment]
Not working on CodePen :(

https://codepen.io/wrathchaos/pen/xxxQdxx

@nurgasemetey  @SchemeSonic  @starikcetin

**Comment by starikcetin** [comment]
Got it working in JsFiddle:

https://jsfiddle.net/starikcetin/9vL1w75c/2/

You need to reference the url without "browse" in it:

Not OK: https://unpkg.com/browse/@paraboly/pwc-map-legend@0.0.9/dist/pwc-map-legend.js
OK: https://unpkg.com/@paraboly/pwc-map-legend@0.0.9/dist/pwc-map-legend.js

**Comment by starikcetin** [comment]
Got it working in JsFiddle: https://jsfiddle.net/starikcetin/9vL1w75c/4/

Library URL should be the Raw version, not Browse version.

This is fine: https://unpkg.com/@paraboly/pwc-map-legend@0.0.9/dist/pwc-map-legend.js
This is NOT fine: https://unpkg.com/browse/@paraboly/pwc-map-legend@0.0.9/dist/pwc-map-legend.js

Notice the `/browse/`.

Using the browse version causes this:

![Capture](https://user-images.githubusercontent.com/21353964/68963157-5ac63380-07e7-11ea-8fa9-65e17d162822.PNG)

**Comment by SchemeSonic** [comment]
Nice gotcha 👌

**Comment by starikcetin** [comment]
I'll put it in the Readme and send a PR.

---

Done: https://github.com/Paraboly/pwc-map-legend/pull/9
